//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternInfos
    {
        public int InternId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int DepartmentId { get; set; }
        public int CityId { get; set; }
        public string Email { get; set; }
        public System.DateTime InternshipStartDate { get; set; }
        public System.DateTime InternshipEndDate { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public Nullable<int> HschoolId { get; set; }
        public string OtherName { get; set; }
    
        public virtual Cities Cities { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Hschools Hschools { get; set; }
        public virtual Universities Universities { get; set; }
    }
}
