//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InternDbEntities : DbContext
    {
        public InternDbEntities()
            : base("name=InternDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminInfos> AdminInfos { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Hschools> Hschools { get; set; }
        public virtual DbSet<InternInfos> InternInfos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Universities> Universities { get; set; }
    }
}
